baseURL = 'https://secureot.github.io/'
languageCode = 'es-ar'
title = 'Ekoparty ICS Village'
DefaultContentLanguage = "es"
theme = "hugo-theme-relearn"
hasCJKLanguage = true
metaDataFormat = "yaml"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
#sectionPagesMenu = 'main'

# Enables or disables the loading animations. false activates them. Default is false.
loadfastload = false

# Sets the speed for the page loading effect. Default is 1.0.
loadspeedfactor = 1.0

# Enables or disables the second flyby cursor. Default is false.
loadonepass = false

enableEmoji = true

# Shows expander for submenus.
# Default: false
# If set to true, a submenu in the sidebar will be displayed in a collapsible
# tree view and a clickable expander is set in front of the entry.
# This can be overridden in the page's frontmatter.
collapsibleMenu = true

[params.ui]
    sidebar_menu_compact = true
    ul_show = 1
    sidebar_menu_foldable = true
    sidebar_cache_limit = 1000

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 1

[[params.themeVariant]]
    identifier = 'relearn-dark'
